# Generated by Django 3.0.5 on 2020-07-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='Experience',
            field=models.CharField(default='no experience', max_length=20),
        ),
    ]
