# Generated by Django 3.0.5 on 2020-12-31 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('VaccineID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Vaccine_Name', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('Dosage', models.CharField(max_length=100)),
                ('Cost', models.IntegerField()),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines_payment',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Add', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=30)),
                ('Vaccinename', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.IntegerField()),
                ('exp_month', models.CharField(max_length=30)),
                ('exp_year', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('timeslot1', models.CharField(max_length=15)),
                ('timeslot2', models.CharField(max_length=15)),
                ('timeslot3', models.CharField(max_length=15)),
                ('timeslot4', models.CharField(max_length=15)),
                ('timeslot5', models.CharField(max_length=15)),
                ('dayunavailable1', models.CharField(max_length=10)),
                ('dayunavailable2', models.CharField(max_length=10)),
                ('VaccineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.Vaccines')),
            ],
        ),
    ]
