# Generated by Django 3.0.7 on 2020-12-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_remove_vaccines_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines_payment',
            name='cardnumber',
            field=models.BigIntegerField(),
        ),
    ]
