# Generated by Django 3.0.5 on 2021-01-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0003_auto_20201231_1856'),
        ('vaccines', '0003_auto_20201231_1410'),
    ]

    operations = [
    ]
