# Generated by Django 3.0.7 on 2020-06-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('doctorID', models.IntegerField(primary_key=True, serialize=False)),
                ('docname', models.CharField(max_length=50)),
                ('specialisation', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=70)),
            ],
        ),
    ]
