# Generated by Django 3.0.7 on 2020-06-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Add1',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='register',
            name='Add2',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='register',
            name='Add3',
            field=models.CharField(max_length=65),
        ),
    ]
