# Generated by Django 3.0.7 on 2020-06-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200620_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='confirmpasswd',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='passwd',
            field=models.CharField(max_length=15),
        ),
    ]
