# Generated by Django 3.0.7 on 2020-07-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200624_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
