# Generated by Django 3.0.5 on 2020-09-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20200808_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirmpasswd',
        ),
    ]
