# Generated by Django 3.0.5 on 2020-09-11 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0017_remove_register_confirmpasswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='register',
            name='patientid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
