# Generated by Django 3.0.5 on 2020-12-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20201014_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forgot_Password',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('otp', models.BigIntegerField()),
            ],
        ),
    ]
