# Generated by Django 3.0.5 on 2020-07-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('testID', models.IntegerField(primary_key=True, serialize=False)),
                ('testname', models.CharField(max_length=50)),
                ('testprice', models.IntegerField()),
            ],
        ),
    ]
