# Generated by Django 3.0.5 on 2020-11-27 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('testID', models.IntegerField(primary_key=True, serialize=False)),
                ('testname', models.CharField(max_length=100)),
                ('testprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Labs_payment',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Add', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=30)),
                ('testname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.IntegerField()),
                ('exp_month', models.CharField(max_length=30)),
                ('exp_year', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
