# Generated by Django 3.0.5 on 2020-10-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs_payment',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('patientID', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('Add', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=30)),
                ('testname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.IntegerField()),
                ('exp_month', models.CharField(max_length=30)),
                ('exp_year', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
    ]
