# Generated by Django 3.0.5 on 2020-11-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='testname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labs_payment',
            name='testname',
            field=models.CharField(max_length=100),
        ),
    ]
