# Generated by Django 3.0.5 on 2020-11-27 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0002_labs_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='testname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labs_payment',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labs_payment',
            name='testname',
            field=models.CharField(max_length=100),
        ),
    ]
