# Generated by Django 3.0.5 on 2020-11-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20201121_2257'),
        ('labs', '0002_labs_payment'),
    ]

    operations = [
    ]
