# Generated by Django 3.0.5 on 2020-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_auto_20201127_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs_payment',
            name='bookingID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
