# Generated by Django 3.0.5 on 2020-09-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='aptid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
