# Generated by Django 3.0.5 on 2020-07-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labs',
            old_name='test_name',
            new_name='testname',
        ),
        migrations.RenameField(
            model_name='labs',
            old_name='test_price',
            new_name='testprice',
        ),
    ]
